name: esg
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
prefix: /opt/miniconda3/envs/esg
